### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by cpranav93** [SDCCA/DGL-PTM#22]
Now that the model is functional, would be good to add unit tests to perform CI for future commits.

**Comment by SarahAlidoost** [comment]
Todo: 
- [x] use pyproject.toml see #57
- [x] add github workflow that builds the package and runs the tests see #57
- [ ] add tests for each module (preferably separate pull requests)
   - [x] agent see #61 
   - [x] agent interaction see #63 
   - [x] network see #64 
   - [x] model see https://github.com/SDCCA/DGL-PTM/pull/84

@meiertgrootes what do you think about this todo list to address this issue?
